[package]
name = "dxgcap"
version = "0.0.2"
authors = ["bryal <96.bryal@gmail.com>"]
description = "Screen capture with DXGI in rust"
repository = "https://github.com/bryal/dxgcap-rs"
documentation = "http://bryal.github.io/dxgcap-rs/dxgcap/"
readme = "README.md"
keywords = ["Windows", "DXGI", "Direct3D", "screen capture", "capture"]
license = "MIT"

[dependencies]
winapi = "*"
dxgi-win = "*"
d3d11-win = "*"